version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auragram
      - JWT_SECRET=ffc35069a810d9c5d06aca52ce6a551a49e0a6a102460cae109877d195d643f553fa0fa3b5bad3a729d43b1cbc955c08691706a0181e487c187b8deb82d7619e
      - PORT=5000
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 