version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/instagram-clone
      - JWT_SECRET=your_jwt_secret
      - HOST=0.0.0.0
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 